import {
  chmodSync,
  cpSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { basename, dirname, join, resolve } from 'node:path';
import { homedir } from 'node:os';
import {
  checkCommand,
  expandHome,
  findZoneRoot,
  getPackageRoot,
  getVersion,
  heading,
  info,
  log,
  readJson,
  run,
  sha256File,
  warn,
  writeJson,
} from './utils.mjs';

export const MARKETPLACE_NAME = 'cgg';
export const PLUGIN_NAME = 'context-grapple-gun';
export const PLUGIN_ID = `${PLUGIN_NAME}@${MARKETPLACE_NAME}`;

export const FULL_SKILLS = [
  './cgg-runtime/skills/cadence/',
  './cgg-runtime/skills/review/',
  './cgg-runtime/skills/siren/',
  './cgg-runtime/skills/statusline/',
  './cgg-runtime/skills/governance-check/',
  './cgg-runtime/skills/governance-mandate-cycle/',
  './cgg-runtime/skills/cadence-downbeat/',
  './cgg-runtime/skills/cadence-syncopate/',
  './cgg-runtime/skills/grapple/',
];

export const SKILLS_ONLY = [
  './cgg-runtime/skills/cadence/',
  './cgg-runtime/skills/review/',
  './cgg-runtime/skills/siren/',
  './cgg-runtime/skills/cadence-downbeat/',
  './cgg-runtime/skills/cadence-syncopate/',
  './cgg-runtime/skills/grapple/',
];

const PACKAGE_PAYLOAD = [
  '.claude-plugin',
  'hooks',
  'cgg-runtime',
  'SESSION_LEARNING_PROTOCOL.md',
  'README.md',
  'START-HERE.md',
  'INSTALL.md',
  'LICENSE',
  'package.json',
];

const AUDIT_DIRECTORIES = [
  'audit-logs/tics',
  'audit-logs/signals',
  'audit-logs/cprs',
  'audit-logs/conformations',
  'audit-logs/economy',
  'audit-logs/provenance',
  'audit-logs/reviews',
  'audit-logs/governance',
];

const TICIGNORE_TEMPLATE = `# Generated by Context Grapple Gun v5\nnode_modules/\ndist/\ntarget/\n.git/\n__pycache__/\n*.pyc\n\n# Vendor/upstream source is not the governed project surface.\nvendor/\n\n# Installed skill templates contain examples, not live CogPRs.\n.claude/skills/\n\n# Stage artifacts are reference and learning material, not tic/signal emitters.\nstage/\n`;

function validateModeAndScope(mode, scope) {
  if (!['full', 'skills', 'convention'].includes(mode)) {
    throw new Error(`Unknown install mode: ${mode}. Use full, skills, or convention.`);
  }
  if (!['user', 'project'].includes(scope)) {
    throw new Error(`Unknown install scope: ${scope}. Use user or project.`);
  }
}

export function resolveInstallTarget({ scope = 'user', zoneRoot, target } = {}) {
  const zone = zoneRoot || findZoneRoot();
  if (target) return resolve(expandHome(target));
  if (scope === 'project') return join(zone, '.claude', 'cgg');
  return join(homedir(), '.cgg', 'context-grapple-gun');
}

export function buildPluginManifest(mode, version, baseManifest) {
  const manifest = structuredClone(baseManifest);
  manifest.version = version;
  manifest.skills = mode === 'skills' ? [...SKILLS_ONLY] : [...FULL_SKILLS];

  if (mode === 'skills') {
    delete manifest.agents;
    delete manifest.hooks;
  }

  return manifest;
}

export function buildMarketplaceManifest(version, baseMarketplace) {
  const marketplace = structuredClone(baseMarketplace);
  marketplace.plugins = marketplace.plugins.map((entry) => {
    if (entry.name !== PLUGIN_NAME) return entry;
    return {
      name: PLUGIN_NAME,
      source: './',
      description: entry.description,
      version,
      strict: true,
    };
  });
  return marketplace;
}

function checkPrerequisites(mode) {
  if (mode === 'convention') return;

  heading('Checking prerequisites...');
  const missing = [];

  if (!checkCommand('claude')) missing.push('claude');
  else info(`  claude .......... ${run('claude', ['--version'], { silent: true })?.trim() || 'found'}`);

  if (!checkCommand('python3')) missing.push('python3');
  else info('  python3 ......... found');

  if (mode === 'full') {
    if (!checkCommand('bash')) missing.push('bash');
    else info('  bash ............ found');
  }

  if (missing.length) {
    throw new Error(`Missing required prerequisites: ${missing.join(', ')}.`);
  }
}

function copyEntry(source, destination) {
  if (existsSync(destination)) rmSync(destination, { recursive: true, force: true });
  mkdirSync(dirname(destination), { recursive: true });
  cpSync(source, destination, { recursive: true, preserveTimestamps: true });
}

function chmodExecutableTree(root) {
  if (!existsSync(root)) return;
  for (const entry of readdirSync(root, { withFileTypes: true })) {
    const path = join(root, entry.name);
    if (entry.isDirectory()) chmodExecutableTree(path);
    else if (/\.(sh|py|mjs)$/.test(entry.name)) chmodSync(path, 0o755);
  }
}

export function copyPackagedRuntime(target, opts = {}) {
  const sourceRoot = opts.sourceRoot || getPackageRoot();
  const absTarget = resolve(expandHome(target));
  const sourceResolved = resolve(sourceRoot);
  const targetIsSourceCheckout = existsSync(join(absTarget, '.git'));

  if (absTarget === sourceResolved) {
    if (opts.mode === 'skills') {
      throw new Error('Skills-only installation requires a separate managed target; refusing to rewrite the source checkout manifest.');
    }
    return {
      target: absTarget,
      copied: false,
      sourceRoot: sourceResolved,
      managedTargetKind: 'source_checkout',
      removalAuthorized: false,
    };
  }

  if (existsSync(absTarget)) {
    const entries = readdirSync(absTarget);
    const isManaged = existsSync(join(absTarget, '.cgg-install.json')) || targetIsSourceCheckout;
    if (entries.length && !isManaged) {
      throw new Error(`Refusing to overwrite non-managed, non-git directory: ${absTarget}`);
    }
  }

  mkdirSync(absTarget, { recursive: true });

  for (const relative of PACKAGE_PAYLOAD) {
    const source = join(sourceResolved, relative);
    if (!existsSync(source)) {
      if (relative === 'LICENSE') continue;
      throw new Error(`npm payload is incomplete: missing ${relative}`);
    }
    copyEntry(source, join(absTarget, relative));
  }

  chmodExecutableTree(join(absTarget, 'hooks'));
  chmodExecutableTree(join(absTarget, 'cgg-runtime', 'hooks'));
  chmodExecutableTree(join(absTarget, 'cgg-runtime', 'scripts'));

  return {
    target: absTarget,
    copied: true,
    sourceRoot: sourceResolved,
    managedTargetKind: targetIsSourceCheckout ? 'source_checkout' : 'package_copy',
    removalAuthorized: !targetIsSourceCheckout,
  };
}

export function writeModeManifests(target, mode, version, opts = {}) {
  const sourceRoot = opts.sourceRoot || getPackageRoot();
  const basePlugin = readJson(join(sourceRoot, '.claude-plugin', 'plugin.json'));
  const baseMarketplace = readJson(join(sourceRoot, '.claude-plugin', 'marketplace.json'));
  const plugin = buildPluginManifest(mode, version, basePlugin);
  const marketplace = buildMarketplaceManifest(version, baseMarketplace);

  writeJson(join(target, '.claude-plugin', 'plugin.json'), plugin);
  writeJson(join(target, '.claude-plugin', 'marketplace.json'), marketplace);

  return { plugin, marketplace };
}

export function ensureZoneSurfaces(zoneRoot, opts = {}) {
  const zone = resolve(zoneRoot);
  const actions = [];
  const dryRun = Boolean(opts.dryRun);
  const tz = process.env.TZ || Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC';

  const ticzonePath = join(zone, '.ticzone');
  if (!existsSync(ticzonePath)) {
    actions.push(`create ${ticzonePath}`);
    if (!dryRun) {
      writeJson(ticzonePath, {
        name: `${basename(zone)}-zone`,
        tz,
        include: ['.'],
        bands: ['PRIMITIVE', 'COGNITIVE', 'SOCIAL'],
        muffling_per_hop: 5,
      });
    }
  }

  const ticignorePath = join(zone, '.ticignore');
  if (!existsSync(ticignorePath)) {
    actions.push(`create ${ticignorePath}`);
    if (!dryRun) writeFileSync(ticignorePath, TICIGNORE_TEMPLATE, 'utf-8');
  }

  for (const relative of AUDIT_DIRECTORIES) {
    const path = join(zone, relative);
    if (!existsSync(path)) {
      actions.push(`create ${path}/`);
      if (!dryRun) mkdirSync(path, { recursive: true });
    }
  }

  return actions;
}

export function appendConventionBlock(zoneRoot, opts = {}) {
  const zone = resolve(zoneRoot);
  const sourceRoot = opts.sourceRoot || getPackageRoot();
  const dryRun = Boolean(opts.dryRun);
  const protocolPath = join(sourceRoot, 'SESSION_LEARNING_PROTOCOL.md');
  const protocol = readFileSync(protocolPath, 'utf-8').trim();
  const claudePath = join(zone, 'CLAUDE.md');
  const existing = existsSync(claudePath) ? readFileSync(claudePath, 'utf-8') : '';

  if (existing.includes('CGG:SESSION-LEARNING-PROTOCOL:START') || existing.includes('## Session Learning Protocol (CGG)')) {
    return { changed: false, path: claudePath };
  }

  if (!dryRun) {
    mkdirSync(zone, { recursive: true });
    const header = existing.trim() ? existing.trimEnd() : `# ${basename(zone)}`;
    writeFileSync(claudePath, `${header}\n\n${protocol}\n`, 'utf-8');
  }

  return { changed: true, path: claudePath };
}

function hasMarketplace(value, name) {
  if (Array.isArray(value)) return value.some((item) => hasMarketplace(item, name));
  if (!value || typeof value !== 'object') return false;
  if (value.name === name) return true;
  return Object.entries(value).some(([key, item]) => key === name || hasMarketplace(item, name));
}

function registerPlugin(target, scope) {
  heading('Validating and registering the Claude Code plugin...');
  run('claude', ['plugin', 'validate', target, '--strict'], { passthrough: true });

  const listingRaw = run('claude', ['plugin', 'marketplace', 'list', '--json'], { silent: true });
  let registered = false;
  if (listingRaw) {
    try {
      registered = hasMarketplace(JSON.parse(listingRaw), MARKETPLACE_NAME);
    } catch {
      registered = listingRaw.includes(MARKETPLACE_NAME);
    }
  }

  if (registered) {
    warn('Replacing the dedicated cgg marketplace registration so source, version, and installed bytes cannot diverge.');
    const removed = run('claude', ['plugin', 'marketplace', 'remove', MARKETPLACE_NAME], { silent: true });
    if (removed === null) {
      throw new Error('The existing cgg marketplace could not be replaced. It may be enterprise/seed managed; ask the administrator to update that source.');
    }
  }

  run('claude', ['plugin', 'marketplace', 'add', target, '--scope', scope], { passthrough: true });
  run('claude', ['plugin', 'install', PLUGIN_ID, '--scope', scope], { passthrough: true });

  const details = run('claude', ['plugin', 'details', PLUGIN_ID], { silent: true });
  const plugins = run('claude', ['plugin', 'list', '--json'], { silent: true });
  if (!details || !plugins || !plugins.includes(PLUGIN_NAME)) {
    throw new Error('Claude Code accepted the install command but the plugin could not be verified in the loaded plugin inventory.');
  }

  return { details: details.trim() };
}

function writeInstallReceipt(target, receipt) {
  const pluginManifest = join(target, '.claude-plugin', 'plugin.json');
  const marketplaceManifest = join(target, '.claude-plugin', 'marketplace.json');
  const hooksManifest = join(target, 'hooks', 'hooks.json');

  const value = {
    schema_version: 1,
    package: PLUGIN_NAME,
    installed_at: new Date().toISOString(),
    ...receipt,
    hashes: {
      plugin_manifest_sha256: sha256File(pluginManifest),
      marketplace_manifest_sha256: sha256File(marketplaceManifest),
      hooks_manifest_sha256: existsSync(hooksManifest) ? sha256File(hooksManifest) : null,
    },
  };
  writeJson(join(target, '.cgg-install.json'), value);
  return value;
}

function printPlan({ mode, scope, zoneRoot, target }) {
  heading('CGG installation plan');
  info(`  version .......... ${getVersion()}`);
  info(`  mode ............. ${mode}`);
  info(`  runtime scope .... ${scope}`);
  info(`  zone root ........ ${zoneRoot}`);
  info(`  managed target ... ${mode === 'convention' ? '(none)' : target}`);
}

function printSummary({ mode, scope, zoneRoot, target }) {
  heading('Installation verified');
  log(`CGG ${getVersion()} installed in ${mode} mode.`);
  info(`  Runtime scope: ${scope}`);
  info(`  Zone root:     ${zoneRoot}`);
  if (mode !== 'convention') info(`  Managed source: ${target}`);
  info('');
  info('Primary commands:');
  info('  /context-grapple-gun:cadence  — close the epoch and seal the handoff');
  info('  /context-grapple-gun:review   — human constitutional judgment');
  info('  /context-grapple-gun:siren    — signal manifold operations');
  info('');
  info('Verification: cgg doctor');
  info('Zone history and governance data remain project-local.');
}

export function install(opts = {}) {
  const mode = opts.mode || 'full';
  const scope = opts.scope || 'user';
  validateModeAndScope(mode, scope);

  const zoneRoot = findZoneRoot(opts.projectDir || process.cwd());
  const target = resolveInstallTarget({ scope, zoneRoot, target: opts.target });
  const dryRun = Boolean(opts.dryRun);
  const sourceRoot = opts.sourceRoot || getPackageRoot();

  printPlan({ mode, scope, zoneRoot, target });

  if (mode === 'convention') {
    const convention = appendConventionBlock(zoneRoot, { sourceRoot, dryRun });
    info(`${dryRun ? '[would write]' : convention.changed ? '[written]' : '[exists]'} ${convention.path}`);
    if (!dryRun) printSummary({ mode, scope, zoneRoot, target });
    return { mode, scope, zoneRoot, target: null, dryRun };
  }

  checkPrerequisites(mode);

  if (dryRun) {
    info(`[would copy] ${sourceRoot} -> ${target}`);
    for (const action of ensureZoneSurfaces(zoneRoot, { dryRun: true })) info(`[would ${action}]`);
    const convention = appendConventionBlock(zoneRoot, { sourceRoot, dryRun: true });
    if (convention.changed) info(`[would append] ${convention.path}`);
    info(`[would validate] claude plugin validate ${target} --strict`);
    info(`[would register] ${PLUGIN_ID} at ${scope} scope`);
    return { mode, scope, zoneRoot, target, dryRun };
  }

  heading('Installing versioned runtime payload...');
  const copyResult = copyPackagedRuntime(target, { sourceRoot, mode });
  writeModeManifests(target, mode, getVersion(), { sourceRoot });
  log(`Runtime payload synchronized to ${target}`);

  heading('Creating project-local governance surfaces...');
  for (const action of ensureZoneSurfaces(zoneRoot)) info(`  ${action}`);
  const convention = appendConventionBlock(zoneRoot, { sourceRoot: target });
  info(`  ${convention.changed ? 'appended' : 'present'} ${convention.path}`);

  registerPlugin(target, scope);

  const receipt = writeInstallReceipt(target, {
    version: getVersion(),
    mode,
    scope,
    zone_root: zoneRoot,
    managed_target: target,
    managed_target_kind: copyResult.managedTargetKind,
    removal_authorized: copyResult.removalAuthorized,
    plugin_id: PLUGIN_ID,
  });

  printSummary({ mode, scope, zoneRoot, target });
  return receipt;
}
