import {
  existsSync,
  lstatSync,
  readdirSync,
  readFileSync,
} from 'node:fs';
import { basename, join, relative, resolve } from 'node:path';
import {
  INSTALL_RECEIPT,
  agentPathsForMode,
  loadComponentContract,
  payloadPathsForMode,
} from './distribution-contract.mjs';
import {
  error,
  findCggRoot,
  getPackageRoot,
  getVersion,
  heading,
  info,
  log,
  readJson,
  sha256,
  warn,
} from './utils.mjs';

const VALID_SUBCOMMANDS = ['check', 'diff', 'sync'];
const GENERATED_DIFFERENCES = new Set([
  '.claude-plugin/plugin.json',
  INSTALL_RECEIPT,
]);
const RUNTIME_GENERATED_DIRS = new Set([
  '.git',
  'node_modules',
  '__pycache__',
  '.pytest_cache',
]);
const RUNTIME_GENERATED_SUFFIXES = ['.pyc', '.pyo', '.DS_Store'];

function isRuntimeGeneratedFile(path) {
  return RUNTIME_GENERATED_SUFFIXES.some((suffix) => path.endsWith(suffix));
}

function collectFiles(base, path = base, output = new Map()) {
  if (!existsSync(path)) return output;
  const stat = lstatSync(path);
  if (stat.isFile()) {
    const rel = relative(base, path).replaceAll('\\', '/');
    if (!GENERATED_DIFFERENCES.has(rel) && !isRuntimeGeneratedFile(rel)) {
      output.set(rel, sha256(readFileSync(path)));
    }
    return output;
  }
  for (const entry of readdirSync(path)) {
    if (RUNTIME_GENERATED_DIRS.has(entry)) continue;
    collectFiles(base, join(path, entry), output);
  }
  return output;
}

function payloadFiles(root, items) {
  const output = new Map();
  for (const item of items) {
    const path = join(root, item);
    if (!existsSync(path)) continue;
    if (lstatSync(path).isFile()) {
      const rel = item.replaceAll('\\', '/');
      if (!GENERATED_DIFFERENCES.has(rel) && !isRuntimeGeneratedFile(rel)) {
        output.set(rel, sha256(readFileSync(path)));
      }
    } else {
      const nested = collectFiles(root, path);
      for (const [name, hash] of nested) output.set(name, hash);
    }
  }
  return output;
}

function expectedPayloadFiles(packageRoot, mode) {
  const output = payloadFiles(packageRoot, payloadPathsForMode(mode));

  // Full mode materializes the admitted agent set from cgg-runtime/agents/
  // into the standard plugin-root agents/ directory. Represent that generated
  // runtime surface in the expected map so sync can detect deleted, drifted,
  // or extra loaded agents rather than comparing only the source corpus.
  const contract = loadComponentContract(packageRoot);
  for (const relativePath of agentPathsForMode(contract, mode)) {
    const source = join(packageRoot, relativePath.replace(/^\.\//, ''));
    output.set(`agents/${basename(relativePath)}`, sha256(readFileSync(source)));
  }

  return output;
}

function installedPayloadFiles(target, mode) {
  const output = payloadFiles(target, payloadPathsForMode(mode));

  // agents/ is generated by the installer rather than copied from the package
  // payload. It is always inspected so skills mode also detects residue from a
  // failed full -> skills contraction.
  const agentsRoot = join(target, 'agents');
  if (existsSync(agentsRoot)) {
    for (const [name, hash] of collectFiles(target, agentsRoot)) output.set(name, hash);
  }

  // Full mode already includes hooks/ in payloadPathsForMode(). Skills mode
  // excludes it by contract, so scan any residual root hooks/ as extra runtime.
  if (mode !== 'full') {
    const hooksRoot = join(target, 'hooks');
    if (existsSync(hooksRoot)) {
      for (const [name, hash] of collectFiles(target, hooksRoot)) output.set(name, hash);
    }
  }

  return output;
}

function comparePayload(packageRoot, target, mode) {
  const source = expectedPayloadFiles(packageRoot, mode);
  const installed = installedPayloadFiles(target, mode);
  const rows = [];
  const all = new Set([...source.keys(), ...installed.keys()]);
  for (const path of [...all].sort()) {
    const sourceHash = source.get(path) || null;
    const installedHash = installed.get(path) || null;
    let status = 'synced';
    if (!sourceHash) status = 'extra_installed';
    else if (!installedHash) status = 'missing_installed';
    else if (sourceHash !== installedHash) status = 'drifted';
    rows.push({ path, status, sourceHash, installedHash });
  }
  return rows;
}

function numericVersion(version) {
  const match = String(version || '').match(/^(\d+)\.(\d+)\.(\d+)/);
  return match ? match.slice(1).map(Number) : null;
}

function compareVersions(a, b) {
  const left = numericVersion(a);
  const right = numericVersion(b);
  if (!left || !right) return null;
  for (let i = 0; i < 3; i += 1) {
    if (left[i] < right[i]) return -1;
    if (left[i] > right[i]) return 1;
  }
  return 0;
}

function loadTarget(targetOverride) {
  const root = findCggRoot(targetOverride);
  if (!root) throw new Error('CGG package target not found. Run: cgg install');
  const receiptPath = join(root, INSTALL_RECEIPT);
  if (!existsSync(receiptPath)) {
    throw new Error(`CGG npm install receipt not found: ${receiptPath}`);
  }
  return { root, receipt: readJson(receiptPath) };
}

function printDiff(rows) {
  const changed = rows.filter((row) => row.status !== 'synced');
  if (!changed.length) {
    log('Package payload and durable target are byte-identical for the receipted mode.');
    return changed;
  }
  for (const row of changed) {
    const writer = row.status === 'extra_installed' ? warn : error;
    writer(`${row.status.padEnd(18)} ${row.path}`);
  }
  return changed;
}

export async function sync(subcommand = 'check', opts = {}) {
  if (!VALID_SUBCOMMANDS.includes(subcommand)) {
    throw new Error(`Unknown sync subcommand: ${subcommand}. Expected: ${VALID_SUBCOMMANDS.join(', ')}`);
  }

  const packageRoot = resolve(opts.packageRoot || getPackageRoot());
  const packageVersion = getVersion();
  const { root, receipt } = loadTarget(opts.target);
  const mode = receipt.mode || 'full';
  const rows = comparePayload(packageRoot, root, mode);

  heading('CGG v5 package reconciliation');
  log(`CLI package: ${packageVersion}`);
  log(`Installed target: ${root}`);
  log(`Receipt package: ${receipt.package_version || 'unknown'}`);
  log(`Receipt mode: ${mode}`);

  if (subcommand === 'diff') {
    const changed = printDiff(rows);
    if (changed.length) process.exitCode = 1;
    return { root, receipt, mode, rows, changed };
  }

  if (subcommand === 'check') {
    const changed = printDiff(rows);
    if (changed.length) process.exitCode = 1;
    const versionState = compareVersions(packageVersion, receipt.package_version);
    if (versionState === -1) {
      error('The running CLI is older than the installed target; refusing to treat it as reconciliation authority.');
      process.exitCode = 1;
    } else if (versionState === 1) {
      warn('A newer CLI package is available to reconcile this target. Run: cgg sync sync');
      process.exitCode = 1;
    } else if (packageVersion !== receipt.package_version) {
      warn('Package versions differ and could not be ordered safely.');
      process.exitCode = 1;
    }
    return { root, receipt, mode, rows, changed };
  }

  const ordering = compareVersions(packageVersion, receipt.package_version);
  if (ordering === -1) {
    throw new Error(
      `Refusing to downgrade target ${receipt.package_version} with older CLI ${packageVersion}.\n` +
      `Run npx context-grapple-gun@${receipt.package_version} sync sync, or install a newer intended version explicitly.`,
    );
  }

  info('Reconciliation is a governed reinstall, not a raw copy into ~/.claude.');
  const { install } = await import('./installer.mjs');
  return install({
    mode,
    scope: receipt.scope,
    target: root,
    zoneRoot: receipt.zone_root,
  });
}
